### ISSUE TITLE
CTeDistribuicaoDFe 3.0

### ISSUE THREAD

**Issue by tiagocardosos** [nfephp-org/sped-cte#103]
@maisonsakamoto, você tem alguma atualização para subir antes de gerar a nova release?

Estive olhando o código atual e não encontrei o método para CTeDistribuicaoDFe. O método será incluíndo na nova release?

Nota técnica - Web Service de Distribuição de DF-e de Interesse dos Atores do CT-e (PF ou PJ)
http://www.cte.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=5c1PwLTdrCA=

**Comment by maisonsakamoto** [comment]
@tiagocardosos eu testei esse método e não funcionou como o esperado, alguns estados da erro, eu acabei não fazendo mais testes posteriores, mas a parte de transmissão e DA esta certinho

**Comment by tiagocardosos** [comment]
@maisonsakamoto, você acha que possível implementarmos o método? Mesmo que este esteja funcionando apenas para alguns estados, te peço, por favor, para evoluirmos a conversa. Tentaremos descobrir as dificuldades com intuito de disponibilizar o método no projeto.

Com a experiência do @robmachado, talvez ele também possa nos dar alguma orientação dos possíveis problemas que você encontrou. De todo modo, farei alguns testes para mapearmos estes problemas.

**Comment by maisonsakamoto** [comment]
oi @tiagocardosos por hora estou alocado em outro projeto, então não posso codificar, mas eu posso acompanhar o progresso e se eu souber ou conseguir ajudar de alguma forma, pode contar comigo.

**Comment by maisonsakamoto** [comment]
@tiagocardosos faça os testes e retorne se ficou tudo ok, obrigado @thmarra por contribuir

**Comment by tiagocardosos** [comment]
@maisonsakamoto, eu a @thmarra trabalhos na mesma equipe!!! Já estamos utilizando a implementação... Continuaremos testando!

**Comment by maisonsakamoto** [comment]
que maravilha! então qualquer coisa se encontrarem dificuldades vai postando, boa sorte!!

**Comment by maisonsakamoto** [comment]
vou deixar em aberto, se vocês se sentirem seguros podem fechar a issue
