### ISSUE TITLE
CT-e Inutilização

### ISSUE THREAD

**Issue by caiquebb** [nfephp-org/sped-cte#109]
Não estou conseguindo realizar a inutilização do CT-e, segue exception recebida:

FatalThrowableError in Tools.php line 370:
Call to undefined method NFePHP\CTe\Tools::zValidParamInut()

**Comment by maisonsakamoto** [comment]
você esta usando o CTe 2.0 ou 3.0 ?

pode mostrar como esta passando os parametros ?

**Comment by caiquebb** [comment]
Estou usando o CTe 2.0

vou colocar os trechos que acho importante.
`
use NFePHP\CTe\Tools;
`
`
$config = '../sped/config/config.json';
$this->cteTools = new Tools($config);
`
`
$retorno = $this->cteTools->sefazInutiliza($request->serie, $request->inicio, $request->fim, $request->justificativa, $this->cteTools->aConfig['tpAmb'], $aResposta);
`

**Comment by caiquebb** [comment]
@maisonsakamoto alguma novidade sobre esta issue?
