### ISSUE TITLE
Undefined offset: -1 nos métodos obsContTag e obsFiscoTag

### ISSUE THREAD

**Issue by wgueds** [nfephp-org/sped-cte#112]
Analisando o método obsContTag encontrei esta linha 

`$posicao = (integer)count($this->obsCont) - 1;`

Como o $this->obsCont no primeiro momento não existe esta ficando -1 ocasionando o erro.

É por algum motivo especial que temos esta lógica?

**Comment by maisonsakamoto** [comment]
Olha como ninguém respondeu até hoje, vou responder, em qual branch esta dando esse erro ?

**Comment by maisonsakamoto** [comment]
já percebi o erro, o motivo de estar escrito desse jeito é porque foi feito um "padrão" para variaveis do tipo Array() note por exemplo que outros metodos que tem variavel array também segue esse exemplo o autor fez o createElement dentro do if, então é erro mesmo vou arrumar o código p/ ti e te aviso na sequencia.

**Comment by maisonsakamoto** [comment]
fiz correção na branch V3.0 e V4.0
https://github.com/nfephp-org/sped-cte/blob/v3.0/src/Make.php
https://github.com/nfephp-org/sped-cte/blob/v4.0/src/Make.php

Caso você esteja usando outra branch favor sinalizar.

**Comment by wgueds** [comment]
Muito obrigado pelo retorno, bacana ;)
