### ISSUE TITLE
Documentação e Instalação

### ISSUE THREAD

**Issue by KaduAmaral** [nfephp-org/sped-cte#120]
Essa biblioteca tem alguma documetação?

Está registrada no Packagist? Consigo instalar com Composer?

**Comment by maisonsakamoto** [comment]
Bom dia,  no README.md diz que consegue instalar usando o comando:
`composer nfephp-org/sped-cte`

Sobre documentação, eu só vi comentários nos códigos, não tenho conhecimento se há um(ou mais) arquivos que sejam exclusivamente documental.

Tem exemplos prontos de como consumir os serviços da sefaz, isso fez com que eu adotasse esse projeto, se precisar de ajuda para fazer os testes pode postar aqui que eu assim que possível irei respondendo.

**Comment by KaduAmaral** [comment]
Ok, obrigado. Estou pensando em adota-lo também e contribuir a medida do possível.
