### ISSUE TITLE
Como assinar o XML com um certificado digital?

### ISSUE THREAD

**Issue by KaduAmaral** [nfephp-org/sped-cte#121]
Como faço pra assinar o CT-e com um certificado digital? A princípio vou ter certificados diferentes para emitentes diferentes. É possível fazer isso?

**Comment by maisonsakamoto** [comment]
Olha eu uso o mesmo certificado digital para N filiais e para a matriz da empresa.

mas respondendo a sua pergunta na pasta install, quando aberta pelo navegador tem entre as configurações de parâmetros a geração das chaves public, private, e cert com extensão .pem quando passado a chave .pfx

E para assinar a classe Tools.php tem um método assina() que faz o serviço.
Dê uma olhada no arquivo testaMakeCTe.php dentro da pasta examples lá mostra como preencher um CT-e, assinar e transmitir.

**Comment by KaduAmaral** [comment]
Eu não vou precisar gerar os certificados, pq a princípio já vou te-los. Parece-me que é exatamente isso que preciso, vou dar uma olhada no método mencionado e no arquivo. Obrigado.

**Comment by paseto** [comment]
O meu caso acho que é parecido com o seu, tenho o cadastro de várias empresas e suas filiais com diferentes certificados.
Cada registro de empresa tem suas configurações para o certificado dela, depois é só chamar esses parâmetros quando instanciar a classe CT-e.
No caso estou usando a v4.0(dentro da pasta examples mostra como fazer o uso do certificado), não há mais a pasta install, por isso é interessante guardar as informações no banco de dados e depois montar um json para utilizar o certificado, ou já guardar o json montado e chamar quando for utilizar a _Tools_.

**Comment by renatotbueno** [comment]
Tem alguma forma de listar todas as CTes com base no CNPJ do tomador?
