### ISSUE TITLE
Como incluir o caminhão transportador

### ISSUE THREAD

**Issue by BENHURMARQUES** [nfephp-org/sped-cte#122]
Pessoal, não estou conseguindo entender como incluir o caminhão transportador e o motorista.
Mudou alguma regra? Não é mais necessário incluir ???

**Comment by maisonsakamoto** [comment]
qual é a tag ?

**Comment by BENHURMARQUES** [comment]
Seria a tag: veicNovos 

Entendi que não é preciso informar o caminhão na 3, correto? 
No teu exemplo você não informa.

nome | tipo | tam. | obrig. | descrição
-- | -- | -- | -- | --
chassi | string | 17 | sim | informar o chassi do veículo.
cCor | string | 1-4 | sim | informar a cor do veículo. código de cada montadora.
xCor | string | 1-40 | sim | informar a descrição da cor.
cMod | string | 1-6 | sim | informar o código marca modelo. Utilizar tabela do RENAVAM.
vUnit | double | 13,2 | sim | informar o valor unitário do veículo. (15 posições, sendo 13 inteiras e 2 decimais).
vFrete | double | 13,2 | sim | informar o valor do frete unitário. (15 posições, sendo 13 inteiras e 2 decimais).

**Comment by maisonsakamoto** [comment]
Na documentação a TAG veicNovos de numero 353 diz que é 0-n ou seja não é obrigatória(0) e também se quiser informar pode informar "n" vezes, eu uso a versão 3.0 no produção e não informo essa tag

**Comment by BENHURMARQUES** [comment]
Então na v3 não é obrigatório informar o caminhão transportador? Fico facultativo? 
Você já está com o v3 em produção? O CT-e emitidos já passaram por alguma fiscalização da ANTT??

**Comment by maisonsakamoto** [comment]
olha posso estar enganado mas a tag veic do modal foi removida essa tag era referente ao caminhão que transporta o CTe, já essa tag veicNovos não é para registrar o veiculo que esta transportando o cte e sim para registrar veículos que estão "dentro" do cte, esses veículos(no plural) são veículos que serão transportados(novos tipo veículos que ficam no caminhão cegonha)  e não veículos transportadores do cte que esta sendo emitido.

**Comment by LUCASNDIAS** [comment]
@BENHURMARQUES , algumas coisas mudaram com a V3. A maior mudança foi na parte de veiculos, seguros e motoristas (neste caso estou falando de transportador e não de veículos sendo transportados). Todos esses campos foram "migrados" para o MDFe (obrigatório de se emitir). Assim, se você tem um transporte de MG para SP com 10 CTes, você não precisará informar o seguro e veículo em nenhum, apenas no Manifesto de Transporte.

A classe de mdfe está funcional na v3 também.
