### ISSUE TITLE
Tag <seg> para o CT-e 3.00

### ISSUE THREAD

**Issue by wgueds** [nfephp-org/sped-cte#123]
Olá pessoal, estou com um problema, estou tentando utilizar a branch v3.0 com os ajustes para a versão 3.00 do CT-e, porem esta dando problema com a TAG seg.

`array(object(DOMElement)), 'Falta tag "seg"')`

Olhando o arquivo de exemplo da v3.0 (https://github.com/nfephp-org/sped-cte/blob/v3.0/examples/testaMakeCTe.php) notei que não esta contemplado esta parte do XML, será que temos um possível problema com isso? no meu caso não estou conseguindo gerar a CT-e.

Notei que no arquivo Make.php no método montaCTe() esta TAG é referenciada dentro o elemento `$this->infCTeNorm`, ao dar print no objeto vi que a TAG seg não esta dentro deste elemento e sim um nível acima, pode ser que seja a causa do problema.

Aguardo e obrigado.

**Comment by aloisogomes** [comment]
Cara tive o mesmo problema, na classe make procure pela linha que adiciona esse nó. Essa tá da problema pois estamos tentando inserir um array diretamente. A solução é apenas colocar dentro de um foreach e inserir o valor da tá.  Isso pq essa tag aceita 0 ou mais valores

**Comment by Rafabin** [comment]
Só ler o manual da versão 3.0 vc vai saber que essa tag não é mais necessária no CTe (assim como veic) e se não me engano é informada no MDFe que acompanha o CTe.

**Comment by Rafabin** [comment]
Campos que migraram para o MDFe 3.0

Dados da seguradora e apólice;
Código Identificador da Operação de Transporte (CIOT);
Dados do(s) veículos;
Dados do(s) motorista(s);
Informações sobre cargas perigosas;
Informações de Vale Pedágio;
Data de previsão da entrega da(s) mercadoria(s);
Local de coleta e local de entrega.

**Comment by paseto** [comment]
Branch v3.0 não recebe mais atualizações. Qualquer dúvida pode abrir outra issue.
