### ISSUE TITLE
Ausência de tags "veic" e "moto"

### ISSUE THREAD

**Issue by aloisogomes** [nfephp-org/sped-cte#126]
Pessoal notei que na classe Make os métodos "veicTag" (para identificação do veículo que será usado para o transporte) e "motoTag" (Identificação do motorista), estão ausentes. Caso não estejam ausentes por favor me informem qual método deve ser utilizado.

**Comment by gustavodebiasi** [comment]
Opa @aloisogomes,
Se estiver utilizando para a emissão de CT-e Outros Serviços, temos a tag veicCTeOSTag,
e se não me engano tem o veicTag, porém, acredito que na versão 3.0 não tem mais veículo no CT-e normal.

**Comment by aloisogomes** [comment]
Bacana vou consultar melhor a documentação para a versão 3

Em 23/11/2017 13:45, "Gustavo Debiasi" <notifications@github.com> escreveu:

**Comment by LUCASNDIAS** [comment]
@aloisogomes ,

Agora os dados de veículos são inseridos no Manifesto (MDF-e) que já está obrigatório pra quaisquer tranportes!

**Comment by aloisogomes** [comment]
@LUCASNDIAS sua informação foi e será vital para quem está implementando CT-e, o manifesto realmente é obrigatório, nem me atentei que devo passar a colocar lá! Muito obrigado mesmo, mas parece que o projeto do MDF-e aqui está ainda em alpha certo?

**Comment by gustavodebiasi** [comment]
@aloisogomes eu utilizo o repositório do MDF-e em produção, na época que implantei tive que fazer várias alterações, mas agora não tive problemas.

**Comment by aloisogomes** [comment]
@gustavodebiasi eu já testei, essas tags agora são inclusas no MDF-e na v3.0. Mas obrigado de verdade.
