### ISSUE TITLE
Preciso de uma ajuda urgente!

### ISSUE THREAD

**Issue by charlesonline** [nfephp-org/sped-cte#128]
Olá pessoal, estou com um problema, acabei não realizando a mudança do meu emissor CTe 2.0 para o 3.0 e estou tendo que desenvolver em produção!

Gostaria de saber se alguém tem as mudanças de campos entre as duas CTes? como foi feito na NFe, ex.:
https://github.com/nfephp-org/sped-nfe/blob/master/docs/EstruturaTxt.md

Estou lendo os manuais, mas percebo que irei demorar muito, se alguém souber de algo..

Abç e obrigado

**Comment by Rafabin** [comment]
rafaelramon87 (skype)
