### ISSUE TITLE
Dacte pdf

### ISSUE THREAD

**Issue by cacio** [nfephp-org/sped-cte#133]
Puxei os arquivos da versão 3.00 , mas não encontrei pra gerar o pdf dacte depois que autorizo o CTe , quando eu fiz toda a passagem de função e autorizei o cte quando fui para gerar o pdf não achei em nem um arquivo a função, alguém pode me auxiliar como e aonde acho para gerar o dacte do Cte ?

**Comment by LUCASNDIAS** [comment]
Boa noite,

@cacio , já faz um tempo que as classes estão em repositórios diferentes. Assim, agora temos:

sped-common => repositório com classes que são comuns em todos os projetos (CT-e, NF-e, MDF-e, etc)
sped-cte => repositório com classes específicas de CT-e
sped-da => Repositório com classes para gerar documentos auxiliares (no seu caso, o DACTE)

O repositório nfephp-org/sped-da já está atualizado para a V3.00.

**Comment by maisonsakamoto** [comment]
Conforme o @LUCASNDIAS mencionou segue o link:
https://github.com/nfephp-org/sped-da

**Comment by cacio** [comment]
Ah blz obrigado, então eu vo ter que baixar o repositório dele separado mas eu não tenho como vincular o repositório junto ao projeto 3.00 junto ao composer ?  sera que consigo ter no mesmo ou eu vo ter que ter pasta separadas tipo speedcte e um sped-da ?

**Comment by maisonsakamoto** [comment]
Eu optei por fazer pastas separadas porque uso a pasta sped-da para emitir tanto o CT-e quando o MDFe, então vai de cada caso

**Comment by cacio** [comment]
@maisonsakamoto  ah tranquilo sem erro só queria ver se dava pra fazer, mas o bom é separada mesmo obrigado desde já

**Comment by cacio** [comment]
@maisonsakamoto  cara como tu fez pra funcionar a geração do sped-da porque eu instalei ele via comando composer e to passando todos os parametros mas quando vo executar ele da um erro chegando na classe $dacce = new Dacce($docxml, 'L', 'A4', '', 'I', '');  da erro na pagina , segue abaixo;
Esta página não está funcionando
localhost não consegue atender a esta solicitação no momento.
HTTP ERROR 500
