### ISSUE TITLE
Listagem de CTe por CNPJ do tomador

### ISSUE THREAD

**Issue by renatotbueno** [nfephp-org/sped-cte#140]
Há alguma forma de listar as CTe com base no CNPJ do tomador?

**Comment by NewtonMan** [comment]
Olá amigo,

Isso deve ser feito pelo seu sistema.

O objetivo dessa API é criar, assinar, validar e transmitir o XML para a SEFAZ, quem estabelece o comportamento é o sistema onde você implementa o CTe.

Abs
