### ISSUE TITLE
Envio de Email

### ISSUE THREAD

**Issue by cacio** [nfephp-org/sped-cte#147]
Fui tentar testar o envio do email do cte mas vi que la não funciona o envio do email , também tentei puxar o a outra pasta speedmail puxei pelo composer e fui  testar o envio do email por ele também não funciona alguma solução para isso ?

**Comment by maisonsakamoto** [comment]
Oi Cacio então até onde sei o email foi separado do projeto cte, não uso o projeto sped-email então não sei o que pode ser, teria que abrir essa issue lá, aqui o que posso dizer é que foi descontinuada
