### ISSUE TITLE
Tools->sefazValidate()

### ISSUE THREAD

**Issue by marcelonogueira** [nfephp-org/sped-cte#152]
Olá, possuo um sistema que recebe NFe's e CTe's para comprovação de compras e vendas realizadas para que o pagamento de subvenções sejam feitas.

Esse sistema recebe os arquivos XML (NFe e CTe). Para o caso da NFe consigo validar se é um arquivo válido utilizando o método NFePHP\NFe\Tools->sefazValidate($nfe) e funciona corretamente. O projeto sped-cte possui também o método NFePHP\CTe\Tools->sefazValidate($cte), porém verifiquei que ele é uma cópia do que existe no projeto sped-nfe. 

Após realizar as alterações na classe NFePHP\CTe\Tools:
De: 
```
Signer::isSigned($cte);
...
$infNFe  = $dom->getElementsByTagName('infNFe')->item(0);

```
Para: 
```
Signer::isSigned($cte, 'infCte');
...
$infNFe  = $dom->getElementsByTagName('infCte')->item(0);
```

Apresentou a mensagem de erro:
```
An error occurred while trying to communication via soap,  [https://cte.svrs.rs.gov.br/ws/cteconsulta/CteConsulta.asmx]HTTP/1.1 500 Internal Server Error
Cache-Control: private
Content-Type: application/soap+xml; charset=utf-8
Server: Microsoft-IIS/7.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 22 Mar 2018 18:48:44 GMT
Content-Length: 540
```

Podem me informar se é possível alterar a classe NFePHP\CTe\Tools para validar na Sefaz ou vocês acham que posso fazer apenas a verificação do DigestValue do arquivo utilizando apenas o método Signer::isSigned()?

**Estou usando a versão sugerida no github: composer require nfephp-org/sped-cte:dev-master.**

**Comment by marcelonogueira** [comment]
Alguma sugestão sobre isso?

Obrigado.

**Comment by NewtonMan** [comment]
Acredito que pelo outro issue aberto por você este você pode fechar.
