### ISSUE TITLE
Erro ao tentar enviar o CTe - [facet 'pattern'] The value 'ISENTO' is not accepted by the pattern '[0-9]{0,14}|ISENTO'

### ISSUE THREAD

**Issue by hecktorvn** [nfephp-org/sped-cte#153]
Ao tentar enviar um CTe está aparecendo a seguinte mensagem:
**This XML is not valid. Element '{http://www.portalfiscal.inf.br/cte}IE': [facet 'pattern'] The value 'ISENTO' is not accepted by the pattern '[0-9]{0,14}|ISENTO'.**

tentei de varias formas o nome ISENTO e não passou, então fui nos esquemas e mudei de 
**[0-9]{0,14}|ISENTO** para **([0-9]{0,14})|ISENTO** e passou, gostaria de saber se tem outra forma de corrigir sem alterar o esquema!

**Comment by LUCASNDIAS** [comment]
Até onde eu me lembro, isso é um problema antigo na validação no PHP. Acabei trocando também, mas troquei apenas a ordem, colocando o ISENTO primeiro. Não lembro de outro solução no grupo!

**Comment by paseto** [comment]
Correto senhores, este problema realmente ocorre, porém não se trata de um erro da API. 
A solução momentânea é esta proposta pelo Lucas > ISENTO|[0-9]{0,14}

**Comment by vmourarosaaa** [comment]
Olá, essa solução ainda funciona? Troquei a ordem da pattern e o erro continua aparecendo.
