### ISSUE TITLE
O digest é diferente - testaAddProtocoloCTE.php

### ISSUE THREAD

**Issue by marcelfenerich** [nfephp-org/sped-cte#154]
Estou tentando utilizar o testaAddProtocoloCTE.php, mas quando utilizo o xml gerado pelo testaMakeCTe.php ele dá um erro: "O digest é diferente.".

Inclusive no arquivo Complements.php ele já dá um warning na linha 120 pq não encontra a tag "DigestValue" no xml. 

Eu verifiquei o arquivo make.php e não existe função para criar esta tag do digest value.

Então concluo: 

De duas, uma; ou as funções do testaAddProtocoloCTE não são feitas para serem usadas neste arquivo gerado pelo pelo testaMakeCTe, ou o está faltando implementar isto.

Mas de qualquer forma, poderiam me responder qual seria exatamente a função do testaAddProtocoloCTE.php? Eu verifiquei que ele apenas gera um arquivo muito parecido com o arquivo xml original.

**Comment by NewtonMan** [comment]
Olá @marcelfenerich acredito que estes exemplos não estejam vigentes na versão de documento que você está tentando usar, há uma transição em andamento dos padrões para seguir o projeto sped-nfe que implementa recursos comuns através do sped-common, que é o caso da assinatura, acho que este exemplo está em desacordo com este padrão, usando o método Complements::toAuthorize acredito ser possível protocolar CTe também, pode validar isso e retornar aqui?

**Comment by paseto** [comment]
Os exemplos da pasta examples são apenas para orientação, no caso o testaAddProtocoloCTE.php  adiciona o protocolo de aprovação da Sefaz no CT-e emitido através do testaMakeCTe.php, este que cria o xml.
Se houver dúvidas reabra outra issue para nova verificação.
