### ISSUE TITLE
autorizadores.json MG Sem o serviço

### ISSUE THREAD

**Issue by cleitonsoares** [nfephp-org/sped-cte#159]
Verifiquei que no arquivo storage/autorizadores.json, para a UF MG, o serviço está vazio, foi acrescentado e gostaria de enviar o pull request, alguém ma auxilia?

**Comment by maisonsakamoto** [comment]
Oi Cleiton, faz um fork desse projeto, no seu fork faça a alteração e depois vai em pull request é só clicar que vai aparecer aqui no projeto para analise e commit
