### ISSUE TITLE
Nome de serviço não bate com switch sefazStatus()

### ISSUE THREAD

**Issue by evertongx** [nfephp-org/sped-cte#16]
Oi,

estou testando o componente e acabei encontrando esse problema, onde a variável  `$servico` dentro do da função `sefazStatus()` está recebendo o valor 'CteStatusServico' e quando passada como parâmetro para `Response::readReturnSefaz($servico, $retorno);` não entra em nenhum case do switch, que no caso esta com o valor 'cteStatusServicoCT'. Se puderem informar o valor correto a ser atribuido (do switch ou da variavel `$servico`) eu posso enviar um pull request com o ajuste.

**Comment by samuelbasso** [comment]
Olá, 

Estou terminando mais umas coisas e já faço um pull request com essa sua solicitação.

**Comment by evertongx** [comment]
@samuelbasso maravilha, fico no aguardo então.

**Comment by samuelbasso** [comment]
@evertongx eu já fiz um push para https://github.com/samuelbasso/sped-cte se quiser conferir. Ainda não fiz o pull request pois executei o comando "composer update" e foi alterado alguma coisa nas bibliotecas commomm que está retornando um problema que não descobri, se poder ajudar também agradeço.

**Comment by robmachado** [comment]
Samuel, que problema está retornando ?? Com o "composer update" ??

**Comment by samuelbasso** [comment]
Oi @robmachado, na realidade foi depois que atualizei as bibliotecas que ao tentar por exemplo gerar e enviar um CT-e começou a ocorrer o erro abaixo:

Fatal error: Uncaught NFePHP\Common\Exception\RuntimeException: Não houve retorno do Curl. name lookup timed out in /Applications/XAMPP/xamppfiles/htdocs/projetos/sped-cte/vendor/nfephp-org/sped-common/src/Soap/CurlSoap.php on line 180

O estranho que em debug eu recebo os retornos da receita que o CT-e foi enviado com sucesso mas no navegador vem esse erro que estou tentando descobrir o que é. Tenho uma cópia antiga antes do "composer update" que está funcionando.

**Comment by samuelbasso** [comment]
Tudo funcionando. Resolvido.

**Comment by evertongx** [comment]
@samuelbasso qual era a causa do erro?

**Comment by samuelbasso** [comment]
A excessão que estava ocorrendo não tinha nada haver com o problema. Como fiz um "composer update" alguns arquivos foram atualizados e perderam as permissões. Depois de horas descobri isso. Refiz as permissões dos arquivos e funcionou.

**Comment by evertongx** [comment]
https://github.com/nfephp-org/sped-cte/commit/831081287182bfab85f04112ace75df38e25c270
