### ISSUE TITLE
Erro de Comunicação CT-e 4.0 no serviço de consulta por chave (Consulta de protocolo)

### ISSUE THREAD

**Issue by mmfla12silva** [nfephp-org/sped-cte#165]
Vi que para a nota fiscal também ocorreu este problema, https://github.com/nfephp-org/sped-nfe/issues/442

**Comment by renandelmonico** [comment]
Realmente, aqui também ocorreu o mesmo erro em conhecimentos do MT. Quando testei com um conhecimento do PR funcionou.

**Comment by mmfla12silva** [comment]
Renan, boa tarde.

Eu usei o programa SOAPui, chamando o serviço de consulta FUNCIONOU, agora
chamando pela biblioteca do SPEED não.
Acho que corpo do ESTRUTURA DO WS está errada.
Vou ver se consigo achar aonde está o erro na estrutura.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-08-04 8:54 GMT-04:00 Renan Delmonico <notifications@github.com>:

**Comment by mmfla12silva** [comment]
Renan, blz.

Achei o problema da Consulta pela Chave do CTE de MT.

O problema estava na estrutura do XML que fica no storage sped-cte.
Este é o arquivo: wscte_3.00_mod57.xml
Está assim:             <CteConsultaProtocolo method='cteConsultaCT' operation='CteConsultaProtocolo ' version='3.00'>https://cte.fazenda.mg.gov.br/cte/services/CteConsulta</CteConsultaProtocolo>

É PARA FICAR ASSIM:
            <CteConsultaProtocolo method='cteConsultaCT' operation='CteConsulta' version='3.00'>https://cte.fazenda.mg.gov.br/cte/services/CteConsulta</CteConsultaProtocolo>

.

O ERRO É NESTE CAMPO DA ESTRUTURA: operation='CteConsultaProtocolo' QUE DEVE SER operation='CteConsulta'

**Comment by mmfla12silva** [comment]
Tinha colocado errado o endereço do serviço, segue abaixo o correto
<CteConsultaProtocolo method='cteConsultaCT' operation='CteConsulta' version='3.00'>https://cte.sefaz.mt.gov.br/ctews/services/CteConsulta</CteConsultaProtocolo>

**Comment by renandelmonico** [comment]
Muito obrigado! Encontrei mais alguns erros, vou corrigir e fazer uma PR

**Comment by renandelmonico** [comment]
PR #168

**Comment by renandelmonico** [comment]
@mmfla12silva o PR #168 foi aprovado, faça um teste agora
