### ISSUE TITLE
Substituição serviço consulta MT

### ISSUE THREAD

**Issue by marcelonogueira** [nfephp-org/sped-cte#170]
A Sefaz de MT alterou o serviço de consulta de CTe no ambiente de produção.

Será necessário alterar a chamada do serviço de:

`<CteConsultaProtocolo method='cteConsultaCT' operation='CteConsultaProtocolo' version='3.00'>https://cte.sefaz.mt.gov.br/ctews/services/CteConsulta</CteConsultaProtocolo>`

Para:
`<CteConsultaProtocolo method='cteConsultaCT' operation='CteConsulta' version='3.00'>https://cte.sefaz.mt.gov.br/ctews/services/CteConsulta</CteConsultaProtocolo>`

**Comment by renandelmonico** [comment]
Olá @marcelonogueira, fiz um Pull Request com essa alteração e estou esperando o review e ver se é aprovado. Você pode acompanhar em #168

**Comment by renandelmonico** [comment]
@marcelonogueira o Pull Request foi aprovado, veja se o problema foi solucionado.

**Comment by marcelonogueira** [comment]
@renandelmonico foi solicionado. Pra manter o sistema daqui rodando eu faço uma substituição no arquivo até que a alteração seja realizada no projeto.

**Comment by renandelmonico** [comment]
@marcelonogueira para não ter que mexer direto no fonte do projeto (se você estiver mexendo direto nele), uma dica é colocar no composer a dependência pegando da master, como eu fiz...
