### ISSUE TITLE
Erro ao emitir CT-e sem informar a tag toma4

### ISSUE THREAD

**Issue by fonini** [nfephp-org/sped-cte#178]
O commit d073a601e4aa8ad7808577cbe472772527890c92 quebrou a emissão do CT-e se não informar a tag **toma4**:

`Fatal error: Uncaught Error: Call to a member function getElementsByTagName() on string in \vendor\nfephp-org\sped-cte\src\Make.php:1589`

Se comentar as linhas adicionadas pelo commit funciona corretamente.

**Comment by paseto** [comment]
Informe seu código para verificar como está sendo montado seu xml.

**Comment by fonini** [comment]
@paseto É o mesmo código desse arquivo [testaMakeCTe.php](https://github.com/nfephp-org/sped-cte/blob/master/examples/testaMakeCTe.php), porém somente comentei esse [bloco](https://github.com/nfephp-org/sped-cte/blob/master/examples/testaMakeCTe.php#L109-L118).

Depois do commit que citei, aparentemente o código tenta pegar o email da tag toma4, mas nesse caso ela não existe.

**Comment by fonini** [comment]
Obrigado!
