### ISSUE TITLE
XML completo do CTE

### ISSUE THREAD

**Issue by alissonrodrigo** [nfephp-org/sped-cte#191]
Bom dia, antes de mais nada estou conhecendo a bibilioteca e estou estudando ela... e gostaria de dar os parabéns a todos os envolvidos....

Minha duvida e a seguinte estou precisando baixar todos os dados de uma cte (eu tenho as chaves), ai faço a consulta e ele me retorna os dados 'resumidos' gostaria de dados completos do remetente, destinatário e outros, alguem sabe me dizer como fazer isso??? Grato

**Comment by paseto** [comment]
Olá @alissonrodrigo ,

Pela API isso não é possível porque a SEFAZ não disponibiliza webservice para tal função.
Somente através de crawlers você conseguirá extrair dados a partir da chave.

Irei encerrar sua issue por não se tratar de uma issue, qualquer outro problema pode abrir uma nova.

**Comment by alissonrodrigo** [comment]
Obrigado, pelo retorno
