### ISSUE TITLE
656 - Rejeicao: Consumo indevido

### ISSUE THREAD

**Issue by viniciuspiloto** [nfephp-org/sped-cte#192]
Boa tarde,
Primeiramente, parabéns pelo projeto, faz exatamente o que eu preciso!
Estou utilizando a ferramenta **sefazDistDFe** para baixar todos os **.xml** de um certificado **.pfx** e estou recebendo a resposta **656 - Rejeicao: Consumo indevido**
Porém, consegui baixar um único CTe na primeira vez que testei a função, depois ele retorna "137 - Nenhum Documento Localizado"
Alguma ideia do que seja? Não estou conseguindo identificar nenhum loop dentro da função que possa gerar esse tipo de erro nem o porquê da mensagem 137.

**Comment by robmachado** [comment]
1 - IMPORTANTE. Leia, estude e entenda a documentação fornecida pela SEFAZ
2 - 656 - Rejeicao: Consumo indevido, se fizer muitas buscas em um pequeno espaço de tempo seu acesso será bloqueado e receberá essa mensagem. Recomendação: rode o loop de busca em backend (sem acesso do usuário) em intervalos não menores que duas horas.
3 - 137 - Nenhum Documento Localizado, esse é um retorno muito comum ao retornar o fim da busca, mas pode ocorrer em outros NSUs também.
