### ISSUE TITLE
XML CT-e completo

### ISSUE THREAD

**Issue by alissonrodrigo** [nfephp-org/sped-cte#197]
Alguem sabe como posso receber o XML ou JSON do ct-e completo? Digo informando todos os dados da nota?

Grato

**Comment by claytonaalves** [comment]
Como assim? Baixando da SEFAZ ?

**Comment by alissonrodrigo** [comment]
Eu estou desenvolvendo um sistema de consulta os dados e para isso preciso da api onde possa me retornar o xml ou json com todos os dados. @claytonaalves  poderia me ajudar onde posso conseguir essa informação?

Grato

**Comment by claytonaalves** [comment]
Infelizmente a SEFAZ não tem nenhuma API que retorne estas informações. Geralmente soluções que que implementam essa funcionalidade utilizam alguma forma de scrapping das páginas da SEFAZ.
