### ISSUE TITLE
Erro faltando a tag infFretamento CTe-os Sefaz PR homologação

### ISSUE THREAD

**Issue by sicoksoftware** [nfephp-org/sped-cte#201]
Boa noite grupo, estou enfrentando o seguinte problema quando tenho enviar para sefaz do meu estado (PR),
está retornado o seguinte erro: Data e hora da viagem deve ser informada para tipo de fretamento eventual. [Det: Informar fretamento eventual ou continuo na tag infFretamento pFretamento]

Dizendo que tenho que informa o data e hora da viagem. mais eu estou procurando na api no Make não encontrei onde gerar essa tag. alguem já possou por esse problema.
desde de já muito obrigado.

deus abençoe

`Array
(
    [retCTeOS] => Array
        (
            [attributes] => Array
                (
                    [versao] => 3.00
                )

            [tpAmb] => 2
            [cUF] => 41
            [verAplic] => PR-v3_0_73
            [cStat] => 837
            [xMotivo] => Data e hora da viagem deve ser informada para tipo de fretamento eventual. [Det: Informar fretamento eventual ou continuo na tag infFretamento pFretamento]
        )

)`

**Comment by paseto** [comment]
Atualizado #202 
Favor efetuar os devidos testes, não utilizo CT-e OS.
```
$fr = new stdClass();
$fr->tpFretamento = 1;
$fr->dhViagem = '';
$cte->infFretamento($fr);
```

**Comment by sicoksoftware** [comment]
Bom dia, não encontrei a função na make, dai eu criei acabei de conseguir autorizar, mais depois que crie, como posso enviar o make.php para vcs verificarem e colocar no repositório.

**Comment by paseto** [comment]
O repositório foi atualizado hoje com a nova tag, se você baixar a versão atual a tag já está presente.
Se possível atualize seu projeto com a nova versão, se houver algo pendente envie sua correção para que todos que utilizam o projeto tenham a mesma versão.

**Comment by sicoksoftware** [comment]
Sim eu ia enviar, mais não sei como, mais você fez da mesma forma que fiz, até nas mesmas linhas :), mais valeu, obrigado caso encontre algum erro envio para vc, muito obrigado, gostaria de poder ajudar com o precisar. valeu forte abraço fique com Deus.
