### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by ricksouza1992** [nfephp-org/sped-cte#206]
Olá, tudo bem?
Pessoal parabéns pelo projeto, está sendo de grande utilidade para meus devidos projetos;
Já venho utilizando a algum tempo e até então nunca tive problemas, na ultima Sexta-feita (21/06/19) tive um problema com o retorno da seguinte mensagem:

**An error occurred while trying to communication via soap, Empty reply from server [https:\/\/nfe.fazenda.sp.gov.br\/cteWEB\/services\/cteStatusServico.asmx];**

Realizei a instalação do certificado na minha maquina e acessei a URL para ver se realmente estava dando algum tipo de erro, mas acessando diretamente consta tudo OK;

Gostaria de saber se alguém já passou por isso e se poderia me dar um help nesta questão;
Agradeço desde já.

**Comment by robmachado** [comment]
O melhor lugar para obter uma resposta é no forum https://groups.google.com/forum/#!forum/nfephp

**Comment by ricksouza1992** [comment]
Ok, vou estar me integrando ao grupo e informando meu problema.

Obrigado.
