### ISSUE TITLE
Averbação de Carga 

### ISSUE THREAD

**Issue by marciotisouza** [nfephp-org/sped-cte#209]
Boa tarde, a parte de averbação de carga poderia ser incluído no sped-cte ou feito outro modulo para ter isso ?

**Comment by robmachado** [comment]
**A averbação não tem nada haver com o CTe,  propriamente dito.**
Averbação é um procedimento obrigatório de comunicação a SEGURADORA com detalhes sobre o frete.
Esse processo requer outra biblioteca, pois a comunicação será feita para outros webservices (desta vez das seguradoras) com os requisitos das mesmas (que podem ser bem diferentes entre si).

**Comment by LUCASNDIAS** [comment]
E tudo sobre seguro e averbação, já está no MDF-e desde a última versão do CT-e! Dados da seguradora e averbação!

**Comment by marciotisouza** [comment]
Bom dia, concordo que o procedimento e separado tanto do CTe como do MDFe. Poderíamos abrir um sped-averbação para contemplar isso ?

Digo isso porque nos meus clientes usamos a averbação da AT&M e Porto Seguro e acredito ser a realidade dos demais colega desenvolvedores, com isso teríamos uma ferramenta mais forte e também iríamos compartilhar experiências neste assunto.

**Comment by robmachado** [comment]
Não vejo porque não faze-lo !
Vou criar um repositório limpo para abrigar o projeto de averbação ai você podem começar a contribuir

**Comment by marciotisouza** [comment]
Maravilha, mas ai você tem que corrigir não sou bom ainda bom php, vim de outras linguagens e apanho um pouco ainda com ele.

**Comment by robmachado** [comment]
ok tendo algo lá vou revisando

**Comment by robmachado** [comment]
Repositório limpo criado, faça o seu fork e suba os PR
https://github.com/nfephp-org/sped-averbacao

**Comment by marciotisouza** [comment]
Maravilha !!!

**Comment by marciotisouza** [comment]
Sobre a averbação da AT&M já tenho funcionando em outra linguagem, ai é só traduzir mas da Porto Seguros não tenho nada, se tiver alguma informação me passa !

**Comment by marciotisouza** [comment]
Boa tarde, desculpe se a pergunta é idiota, mas como nunca participei de um desenvolvimento compartilhado, como irei enviar o que vou fazer se não pode ser via pull request do github ?

**Comment by robmachado** [comment]
É evidente que pode fazer um PR !! faça um FORK do projeto em seu user do github suba as coisas para o seu fork e de lá solicite o PR

**Comment by marciotisouza** [comment]
Ok, vou tentar, grato !!!
