### ISSUE TITLE
Add cancel protocol to a autorized CTe

### ISSUE THREAD

**Issue by phpanico** [nfephp-org/sped-cte#212]
Olá, boa tarde! Gostaria de sugerir a inclusão do método abaixo nas rotinas do Sped-CTe.

 /**
     * Add cancel protocol to a autorized CTe
     * if event is not a cancellation will return
     * the same autorized CTe passing
     * NOTE: This action is not necessary, I use only for my needs to
     *       leave the CTe marked as Canceled in order to avoid mistakes
     *       after its cancellation.
     * @param  string $cte content of autorized CTe XML
     * @param  string $cancelamento content of SEFAZ response
     * @return string
     * @throws \InvalidArgumentException
     */
    public static function cancelRegister($cte, $cancelamento)
    {
        var_dump($cancelamento);
$procXML = $cte;
        $domcte = new DOMDocument('1.0', 'utf-8');
        $domcte->formatOutput = false;
        $domcte->preserveWhiteSpace = false;
        $domcte->loadXML($cte);
        $proCTe = $domcte->getElementsByTagName('protCTe')->item(0);
        if (empty($proCTe)) {
            //not protocoladed CTe
            throw DocumentsException::wrongDocument(1);
        }
        $chaveCTe = $proCTe->getElementsByTagName('chCTe')->item(0)->nodeValue;

        $domcanc = new DOMDocument('1.0', 'utf-8');
        $domcanc->formatOutput = false;
        $domcanc->preserveWhiteSpace = false;
        $domcanc->loadXML($cancelamento);
        $eventos = $domcanc->getElementsByTagName('retEventoCTe');
        foreach ($eventos as $evento) {
            $infEvento = $evento->getElementsByTagName('infEvento')->item(0);
            $cStat = $infEvento->getElementsByTagName('cStat')
                ->item(0)
                ->nodeValue;
            $nProt = $infEvento->getElementsByTagName('nProt')
                ->item(0)
                ->nodeValue;
            $chaveEvento = $infEvento->getElementsByTagName('chCTe')
                ->item(0)
                ->nodeValue;
            $tpEvento = $infEvento->getElementsByTagName('tpEvento')
                ->item(0)
                ->nodeValue;
            if (in_array($cStat, ['135', '136', '155'])
                && $tpEvento == '110111'
                && $chaveEvento == $chaveCTe
            ) {
                $proCTe->getElementsByTagName('cStat')
                    ->item(0)
                    ->nodeValue = '101';
                $proCTe->getElementsByTagName('nProt')
                    ->item(0)
                    ->nodeValue = $nProt;
                $proCTe->getElementsByTagName('xMotivo')
                    ->item(0)
                    ->nodeValue = 'Cancelamento de CT-e homologado';
                $procXML = Strings::clearProtocoledXML($domcte->saveXML());
                break;
            }
        }
        return $procXML;
    }

**Comment by cleitonperin** [comment]
foi criado

**Comment by phpanico** [comment]
Obrigado
