### ISSUE TITLE
Erro na função zGetProt()

### ISSUE THREAD

**Issue by evertongx** [nfephp-org/sped-cte#22]
@samuelbasso  Esta mudança está afetando o retorno do serviço 'CteRetRecepcao', pois não tem número de protocolo quando retorna com erro de validação da SEFAZ.

**Comment by robmachado** [comment]
Que mudança ??? Onde ??

**Comment by evertongx** [comment]
@robmachado perdão, não foi o link. Essa: https://github.com/nfephp-org/sped-cte/commit/df7475f109b600250724dc00fa541b2d7be6e8d9#diff-50f0e86a4e75c7a134ad67c6becc04e3L447

**Comment by robmachado** [comment]
Você é quem fez essa alteração Samuel !!!
Você foi quem retirou a validação do conteúdo do campo. É claro que irá dar erro pois está tentando pegar algo que não existe de foi retornado erro ... com certeza não tem o  numero do protocolo

**Comment by samuelbasso** [comment]
Oi @robmachado, sim foi eu que alterei, mas o problema foi o @evertongx que relatou e não eu como me pareceu na tua resposta. Deixa que ajusto. Eu reviso a função, lembro que retirei pois o nProt estava vindo sempre 1.

**Comment by robmachado** [comment]
Cara desculpa !! eu não tinha reparado nisso ... mas de qualquer forma a resposta foi pro cara certo :8ball:

**Comment by evertongx** [comment]
@samuelbasso comigo esta retornando status 203 e sem protocolo, pq estou sem um certificado válido para emissão de CTe, ocasionando o erro.

**Comment by robmachado** [comment]
É isso mesmo Srs. quando ocorre um erro nessa consulta o campo nProt não é retornado. Então nos temos que verificar e se não for retornado carregar o array com uma string vazia senão será um FATAL ERROR no PHP

**Comment by robmachado** [comment]
Podem e DEVEM haver casos semelhantes a esse !! Fiquem atentos pois os ERROS são comuns.

**Comment by samuelbasso** [comment]
Tudo certo. Foi recolocado um teste da existência do nProt. Já fiz um pull request. Abraço.

**Comment by evertongx** [comment]
resolvido em: https://github.com/nfephp-org/sped-cte/pull/23
