### ISSUE TITLE
Download via chave de acesso [57]

### ISSUE THREAD

**Issue by leoNorml** [nfephp-org/sped-cte#238]
No sped-nfe temos o sefazDownload(); Aonde enviamos a chave de acesso e temos o download do xml. Eu consigo realizar este processo sefazDownload(), no sped-cte?

o dist eu consigo por lote, mas eu gostaria por chave.

**Comment by robmachado** [comment]
De acordo com a [Nota Técnica 2015/002](http://www.cte.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=5c1PwLTdrCA=) não existe um webservice para download do xml do CTe, nos moldes do serviço que existe para NFe.
Isso implica que o download deverá ser feito diretamente na [página de consulta da Receita Federal](http://www.cte.fazenda.gov.br/portal/consultaRecaptcha.aspx?tipoConsulta=completa&tipoConteudo=mCK/KoCqru0=)
Leia o documento da SEFAZ !!

**Comment by mmendescortes** [comment]
Ainda continuamos com esse problema?
