### ISSUE TITLE
Montagem Errada Tag "Entrega"

### ISSUE THREAD

**Issue by willkerms** [nfephp-org/sped-cte#273]
Quando se informa da tag "Entrega" a API monta o XML errado dando o erro ao validar o Schema. 

Para correção deve-se inserir o código da linha 546 `if ($this->fluxo != '') {` até a linha 575, para dentro do método `tagcompl ` após a tag `xEmi` linha 1658.

O arquivo corrigido está em anexo. 

Fiz os comentários em meu nome "Willker", somente pesquisar e achará as correções.

[Make.txt](https://github.com/nfephp-org/sped-cte/files/4066417/Make.txt)

**Comment by mateusperego** [comment]
Fiz os ajustes conforme solicitado, pode conferir e qualquer coisa me avisa.
Obrigado

**Comment by willkerms** [comment]
Ficou um `$this->tagEntrega();` na linha 1660 que é desnecessário com está correção, acredito que seja do commit "e62172965c56c693762e53194b3768adbef20995" anterior ao da correção.

**Comment by mateusperego** [comment]
Desculpe não tinha visto, agora removi.

**Comment by willkerms** [comment]
Só esperar o merge agora
