### ISSUE TITLE
sefazDownload volta erro de SOAP

### ISSUE THREAD

**Issue by mmendescortes** [nfephp-org/sped-cte#305]
Ao executar a função sefazDownload passando como argumento a chave da CTE, tenho como retorno o seguinte:
```json
{
    "error": {
        "code": "NFePHP\\Common\\Exception\\SoapException",
        "message": "Erro de comunica\u00e7\u00e3o via soap,  Requisi\u00e7\u00e3o inv\u00e1lida"
    }
}
```

O que posso fazer para conseguir baixar a CTE?

**Comment by robmachado** [comment]
A SEFAZ/Receita desligaram o processo de busca de documentos destinados por numero de NSU e pela Chave, então esse processo não irá mais funcionar. 
Apenas a busca pelo o ultNSU deve permanecer ! isso se pararem de "ABUSAR" do sistema.

**Comment by mmendescortes** [comment]
> A SEFAZ/Receita desligaram o processo de busca de documentos destinados por numero de NSU e pela Chave, então esse processo não irá mais funcionar. Apenas a busca pelo o ultNSU deve permanecer ! isso se pararem de "ABUSAR" do sistema.

Beleza!

**Comment by robmachado** [comment]
Esses processos já foram religados porem com grandes limitações

**Comment by lramondev** [comment]
Estou recebendo esse erro no método sefazDownload
"NFePHP\Common\Exception\SoapException
Erro de comunicação via soap, Requisição inválida"
