### ISSUE TITLE
CONTINGENCIA PARA O ESTADO DE RN E PI

### ISSUE THREAD

**Issue by YasCarol** [nfephp-org/sped-cte#325]
Ao homologar e ativar a emissão em contingencia de contribuintes dos estado de RN e PI notei que as emissões estão sendo direcionadas para a SVRS quando aparentemente deveriam ser direcionadas para SVSP. 
Quando tento emitir na SVRS eu recebo a rejeição da sefaz : 513 - Rejeicao: UF nao atendida pela SVC-RS e quando altero para a SVSP eu consigo emitir em contingencia, essa alteração é feita no arquivo Contingency na função activate.
Fiz algumas pesquisas e segundo esse doc https://flexdocs.net/guiaCTe/WS.html a SVC dos estados de RN e PI é a SVC de SP. 
Estou fazendo algo errado ou isso deve ser corrigido no projeto?? me ajudem por favor!!

**Comment by YasCarol** [comment]
A forma que estou fazendo é bem simples: $tools->contingency->activate($tools->config->siglaUF, 'Falha de comunicaçao com a SEFAZ'); 
Basicamente passo a UF e a classe define qual SVC utilizar... o problema é que para RN e PI está definido como SVRS e quando altero para SVSP eu consigo emitir... em homologacao pelo menos, talvez seja o ambiente. Espero que em produção funcione.

**Comment by robmachado** [comment]
https://groups.google.com/g/nfephp

**Comment by YasCarol** [comment]
Vide https://www.cte.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=wpdBtfbTMrw=

Acredito que todos os estados que utilizam a SVRS - Sefaz Virtual do RS: AC, AL, AM, BA, CE, DF, ES, GO, MA, PA, PB, PI, RJ, RN, RO, SC, SE, TO é para emissão normal pois não possuem aplicação própria. Todos esses, exceto RN e PI, no projeto estão utilizando SVSP para emissão em contingencia, e nos testes apenas SVSP consegue autorizar de RN e PI...

**Comment by robmachado** [comment]
**RN estava errado** na classe **Contingency.php** apontava para SVRS quando deveria apontar para SVSP.
Todos que usam SVRS em contingência devem apontar para SVSP e vice-versa. Já outros autorizadores apontas para seus parceiros específicos.

Lista de ufs e sua contingência:
'AC' => 'SVSP',
'AL' => 'SVSP',
'AM' => 'SVSP',
'AP' => 'SVRS',
'BA' => 'SVSP',
'CE' => 'SVSP',
'DF' => 'SVSP',
'ES' => 'SVSP',
'GO' => 'SVSP',
'MA' => 'SVSP',
'MG' => 'SVSP',
'MS' => 'SVRS',
'MT' => 'SVRS',
'PA' => 'SVSP',
'PB' => 'SVSP',
'PE' => 'SVRS',
'PI' => 'SVSP',
'PR' => 'SVSP',
'RJ' => 'SVSP',
'RN' => 'SVSP',
'RO' => 'SVSP',
'RR' => 'SVRS',
'RS' => 'SVSP',
'SC' => 'SVSP',
'SE' => 'SVSP',
'SP' => 'SVRS',
'TO' => 'SVSP'

**Comment by YasCarol** [comment]
Show... essa correção será lançada no projeto??

**Comment by robmachado** [comment]
já foi está em dev-master

**Comment by YasCarol** [comment]
Obrigada!
