### ISSUE TITLE
CteConsultaProtocolo

### ISSUE THREAD

**Issue by Reinaldorcm** [nfephp-org/sped-cte#37]
Boa noite.
Primeiramente gostaria de parabeniza-los pelas contribuições no projeto NFePHP, conheci a pouco tempo e estou gostando muito.

bom.... 
Estou testando o SPED-CTE e vi que existe um teste de consulta da chave a qual está funcionando corretamente para a chave do PR utilizada no exemplo ( 41160981450900000132570020000000581000000108), porém quando tendo efetuar uma consulta para qualquer chave de SP é retornado este erro:

 "HTTP/1.1 500 Internal Server Error\r\nCache-Control: private\r\nContent-Type: application/soap+xml; charset=utf-8\r\nServer: Microsoft-IIS/7.5\r\nX-AspNet-Version: 4.0.30319\r\nX-Powered-By: ASP.NET\r\nDate: Thu, 29 Sep 2016 01:58:57 GMT\r\nContent-Length: 500\r\n\r\n"

Já verifiquei que o serviço do SEFAZ SP está on-line  e também já comparei a url do schema:

<CteConsultaProtocolo method='cteConsultaCT' operation='CteConsultaProtocolo' version='2.00'>https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteConsulta.asmx</CteConsultaProtocolo>

Você sabe me dizer se este serviço não funciona para SP ou se é algum erro da aplicação ?

Desde já obrigado pela atenção.

Reinaldo

**Comment by maisonsakamoto** [comment]
Bom dia Reinaldo, se não me engano esse teste de PR é meu, vou testar com o de SP e já te aviso

**Comment by maisonsakamoto** [comment]
Reinaldo, fiz o teste no arquivo testaStatusCTe.php e da erro, então não esta funcionando mesmo, só não sei porque, vou tentar descobrir o porque do send() da Classe  CurlSoap não estar funcionando direito nos outros estados

**Comment by robmachado** [comment]
Tem vários erros ainda nas classes:
Ex. na classe Tools está setado modelo = '65' ??? o correto é modelo = '57'
Não estão corretos os apontamentos aos serviços dos autorizadores para o modelo 57, isso dentre muitas outras falhas

**Comment by maisonsakamoto** [comment]
Bom Dia Reinaldo descobri o problema procure o arquivo BaseTools.php localize a funcao zLoadServico(), tem um trecho de código assim:
//recuperação da versão
        $this->urlVersion = $aURL[$service]['version'];
        //recuperação da url do serviço
        $this->urlService = $aURL[$service]['URL'];
        //recuperação do método
        $this->urlMethod = $aURL[$service]['method'];
        **//recuperacao da operacao - maison 03/10/2016 - em TESTE
        $this->urlOperation=$aURL[$service]['operation'];**
        //montagem do namespace do serviço
        //$this->urlOperation = $aURL[$service]['operation'];
        $this->urlNamespace = sprintf("%s/wsdl/%s", $this->urlPortal, $this->urlOperation);  
        
        //montagem do cabeçalho da comunicação SOAP
        $this->urlHeader = $this->zMountHeader($tipo, $this->urlNamespace, $this->urlcUF, $this->urlVersion);

**Comment by maisonsakamoto** [comment]
Vou fazer o Make p/ testar assim que eu terminar eu vou upar as atualizações já considerando as alterações que o Roberto mencionou.

**Comment by maisonsakamoto** [comment]
Roberto como faz o commit do BaseTools.php?
Estou usando o GIT no NetBeans e a pasta vendor fica toda cinza, não consigo fazer commit de nada que esta lá dentro

**Comment by robmachado** [comment]
@maisonsakamoto 

Eu sugiro por ora que você estendam essa classe no repositório  da CTe. 
O que ocorre é que certas partes dessa classe como esse método é especifico para cada serviço, seja CTe, NFe ou MDFe então essas partes que são diferentes deveriam estar definidas LOCALMENTE e não  na estrutura comum. Eu estou aos poucos mudando isso.

**Comment by maisonsakamoto** [comment]
a Classe Tools.php já extende de BaseTools.php, você quis dizer fazer uma sobrecarga de métodos? 
Vou mandar outro pull p/ vermos se é isso mesmo, aguardo sua analise lá ok.

**Comment by robmachado** [comment]
Ou você estende a classe Base para outra base local, apenas alterando o método necessário ou inclui esse método já alterado dentro da própria classe tools.

**Comment by maisonsakamoto** [comment]
@Reinaldorcm estou fazendo o pull no projeto, se quiser no meu fork já tem ele lá a correção.

**Comment by Reinaldorcm** [comment]
@maisonsakamoto show de bola, agora está funcionando.
Obrigado pelo seu empenho.
;)

**Comment by Reinaldorcm** [comment]
Maison,
Acho você esqueceu de corrigir a tag  **operation** de produção para SP no seu fork
<CteConsultaProtocolo method='cteConsultaCT' operation='**CteConsultaProtocolo**'  (CteConsulta) version='2.00'>https://nfe.fazenda.sp.gov.br/cteWEB/services/cteConsulta.asmx</CteConsultaProtocolo>

**Comment by Reinaldorcm** [comment]
Maison,
Acho você esqueceu de corrigir a tag operation de produção para SP no seu fork
`<CteConsultaProtocolo method='cteConsultaCT' operation='**CteConsulta**' version='2.00'>https://nfe.fazenda.sp.gov.br/cteWEB/services/cteConsulta.asmx</CteConsultaProtocolo>`

**Comment by maisonsakamoto** [comment]
Oi Reinaldo, eu corrigi em ambiente de homologação, mas já vou corrigir o produção também
