### ISSUE TITLE
sefazInutiliza() declarada duas vezes!

### ISSUE THREAD

**Issue by evertongx** [nfephp-org/sped-cte#45]
Compile Error: Cannot redeclare NFePHP\CTe\Tools::sefazInutiliza()

Erro grave esse hein...

**Comment by maisonsakamoto** [comment]
@evertongx se quiser pode usar o meu fork, ainda não entrou aqui o meu ultimo pull

**Comment by maisonsakamoto** [comment]
ops, acabou de entrar..

**Comment by evertongx** [comment]
@maisonsakamoto parace que ainda está lá, só faz assim então, me fala qual desses é o que você ajustou que mando um pull request removendo o outro.

**Comment by maisonsakamoto** [comment]
no [pull #39](https://github.com/nfephp-org/sped-cte/pull/39) eu mandei um monte de correção, acho que depois que eu criei uma BaseTools local já estava corrigido [aqui](https://github.com/nfephp-org/sped-cte/pull/39/commits)

**Comment by robmachado** [comment]
Srs. Usem como sua referencia e testes apenas o branch DEVELOP. E façam seus pull requests apenas nesse branch (DEVELOP) .. quando estiver mais funcional eu mando para master e crio um RELEASE. 
Outra coisa as classes ainda estão BEM sujas com muito código comentado e sem documentações e testes unitários. Eu e outro colega estamos melhorando as classes em sped-common, por ora sem quebrar a compatibilidade mas existem classes novas pra o certificado, assinatura do xml, validação do XML e comunicação SOAP, se interessar posso passar mas informações para vocês.

**Comment by evertongx** [comment]
resolvido https://github.com/nfephp-org/sped-cte/pull/48
