### ISSUE TITLE
Classe Tools.php

### ISSUE THREAD

**Issue by maisonsakamoto** [nfephp-org/sped-cte#50]
temos uma implementação **public function enviaMail()** e havia uma função somente com a assinatura:
**public function mailCTe(){ }** esta estava sem codigos, podemos remover esta última por assumir que a primeira será usada para fazer a mesma coisa ? se são coisas diferentes sugiro melhorar a nomeclatura para ficar mais claro o que cada uma irá fazer

**Comment by robmachado** [comment]
Pode atér ser completamente retirada dai ... tanto a impressão como o envio de email deve ser responsabilidade da aplicação e não da API !
