### ISSUE TITLE
Migração 3.00

### ISSUE THREAD

**Issue by Gleidson2012** [nfephp-org/sped-cte#53]
Como posso contribuir no repositório na implementação da versão 3.00 do CT-e?

**Comment by robmachado** [comment]
Todo o desenvolvimento deverá ser feito sobre a branch develop. 
Caso queira contribuir com código, faça um fork instale localmente e pode codificar.
As contribuições devem ser enviadas por pull request  e devem obedecer ao PSR 2, eu sugiro que abra ISSUES e milestones para as tarefas que se propuser a realizar para que outros não fiquem fazendo as mesmas coisas.

**Comment by Gleidson2012** [comment]
Certo.
Mas quanto a quebra de API? 
Considerando que o branch **develop** implementa a versão 2.00.

**Comment by robmachado** [comment]
Uma mudança de versão como essa sempre irá quebrar algo !! isso é um fato ...
Toda vez que ocorrer uma alteração de versão como essa a API passa de para uma nova versão principal .. se erá 2.?? passa a ser 3.?? ... é interessante que apenas as chamadas para a sefaz e os nomes das  classes seja sempre preservado, já os parametros podem até serem diferentes tendo em vista as alterações.

**Comment by Gleidson2012** [comment]
Então podemos concluir que a versão da API no branch **master** é a versão 2.00, e no branch develop iremos implementar a versão 3.00?

E como  serão definidas as releases?
Consultei nas releases e possuímos a [v1.1.0](https://github.com/nfephp-org/sped-cte/releases/tag/v1.1.0). Podemos definir que a versão 3.00 do CT-e seja implementada na v2.*.

O que acham?

**Comment by robmachado** [comment]
A branch master será mantida até que a develop (3.00) esteja minimamente estável nessa nova versão. Nesse ponto a versão da marter será congelada em uma TAG e a DEVELOP será mergeada a MASTER e uma nova TAG dessa vez com a versão 3.00 será gerada

**Comment by Gleidson2012** [comment]
Perfeito!

Alinhado.
