### ISSUE TITLE
install

### ISSUE THREAD

**Issue by cacio** [nfephp-org/sped-cte#72]
Boa tarde, Só queria saber se essa versão já esta usável fiz install composer nele e vi que falta o install 
 para começar a usar, estou fazendo uma migração no meu sistema atualizando Framework e queria ver se esse projeto esta usável. obrigado.

**Comment by maisonsakamoto** [comment]
Oi @cacio eu também tive que usar a pasta install de outro projeto para setar as configurações do config.json, vou colocar no pull request para o mantenedor verificar a possibilidade de incluir.

Já na questão "usável" se queres dizer se esta montando o xml e transmitindo lhe digo que sim, apesar dos meus testes não usar todas as tags que existem na documentação sa SEFAZ, é possível usar as tags já implementadas e também implementar as demais por conta própria, do jeitinho que esta já é possível obter a "autorização de uso" da SEFAZ.

**Comment by maisonsakamoto** [comment]
esta lá a solicitação https://github.com/nfephp-org/sped-cte/pull/73

**Comment by cacio** [comment]
Sem erro @maisonsakamoto obrigado, vo fechar essa issues
