### ISSUE TITLE
MakeCte

### ISSUE THREAD

**Issue by cacio** [nfephp-org/sped-cte#79]
Bom dia, 
Estou tentando usar esse novo repositório para gerar o cte mas antes estou fazendo uns testes e vejo que não esta usável esta dando alguns erros , segue abaixo os erros , se alguém tiver como me dar um help agradeço.

Fatal error: Call to undefined method NFePHP\CTe\Make::toma3Tag() in C:\xampp\htdocs\PROJETOS\sped-cte\examples\testaMakeCTe.php on line 81

Fatal error: Call to a member function appendChild() on a non-object in C:\xampp\htdocs\PROJETOS\sped-cte\vendor\nfephp-org\sped-common\src\Dom\Dom.php on line 143

**Comment by cleitonsoares** [comment]
Estou com a mesma issue.

**Comment by samuelbasso** [comment]
@cacio @cleitonsoares vocês estão utilizando a release ou a branch master?

**Comment by cleitonsoares** [comment]
@samuelbasso estou usando a branch master.

**Comment by samuelbasso** [comment]
@cleitonsoares Faz um teste para mim na developer e me avisa. Que se estiver tudo funcional eu faço um merge com a master.

**Comment by cleitonsoares** [comment]
@samuelbasso teste feito com o branch develop, o erro não aconteceu. Muito obrigado pela atenção!

**Comment by cacio** [comment]
Teste feito, show, agora foi que nem um mel da chupeta , muito obrigado e agradeço pela atenção

**Comment by samuelbasso** [comment]
Valeu pessoal pela ajuda. Vou enviar para a master as correções. Abraço.
