### ISSUE TITLE
Erro ao utilizar a palavra ISENTO no campo I.E.

### ISSUE THREAD

**Issue by MateusMaiaBH** [nfephp-org/sped-cte#82]
Recebo o seguinte erro ao tentar utilizar a palavra ISENTO:

Algum erro ocorreu....

Elemento '{http://www.portalfiscal.inf.br/cte}IE': [Erro 'Layout'] O valor 'ISENTO' não é aceito para o padrão. '[0-9]{2,14}'. 
Elemento '{http://www.portalfiscal.inf.br/cte}IE': 'ISENTO' não é um valor válido.

**Comment by samuelbasso** [comment]
@MateusMaiaBH essa resposta foi ao autorizar? Pois se for, a mensagem diz '[0-9]{2,14}' significa que não aceita a palavra ISENTO, somente números. Envia um IE ou em branco.

**Comment by MateusMaiaBH** [comment]
Obrigado pela resposta Samuel, eu recebo ela ao rodar o testaMakeCTe, ele chega a criar o XML, mas depois da isso.

Ao mandar em branco recebi esse erro aqui:

Algum erro ocorreu....

Elemento '{http://www.portalfiscal.inf.br/cte}xNome': Este elemento não é esperado. Esperado é ( {http://www.portalfiscal.inf.br/cte}IE ).

**Comment by MateusMaiaBH** [comment]
Preenchi com uma IE qualquer que copiei de outra empresa, e funcionou tudo bacana, como devo proceder nesse caso em que o emitente não tem IE?

**Comment by samuelbasso** [comment]
@MateusMaiaBH opa, agora que falou emitente mudou a situação. Emitente é obrigatório informar IE não tem como informar ISENTO. Sugiro verificar isso ou olhe o manual.

**Comment by MateusMaiaBH** [comment]
Beleza, fiz outro teste aqui com outros dados e deu tudo certinho, obrigado pelas respostas 👍
