### ISSUE TITLE
CTe 3.0 - previsão para versão estável

### ISSUE THREAD

**Issue by BENHURMARQUES** [nfephp-org/sped-cte#94]
Olá pessoal,

Como esta a situação da v3.0? Quero colocar em produção a v2.0 porém antes queria saber se existe previsão de disponibilização da v3.0

Alguém sabe responder???

**Comment by maisonsakamoto** [comment]
Bom a garantia de você entrar nesse barco é que terá a minha companhia, eu trabalho com transportadora no setor de TI, então eu te digo que vou fazer rodar a versão 3.0 até Dezembro sem dúvidas.

Estou bem tranquilo quanto a isso porque a única coisa que muda na versão 3 são as TAGs do xml que é emitido, a forma de transmitir é a mesma, então codificar essa parte é bem simples.

Só não estou fazendo PR agora porque meu ERP tem outras demandas mais urgentes então estou indo por prioridades.

Seja bem vindo, qualquer dúvida pode chamar ai que no que eu souber ajudar eu ajudo, porque "de graça me ajudaram, de graça eu ajudo"

**Comment by maisonsakamoto** [comment]
vou deixar em aberto p/ ver se alguém se propõe e dizer uma "data de previsão", eu me proponho que pelo menos 1 ou 2 meses antes de Dezembro eu já tenha uma versão funcional já para o produção, mas se alguém quiser se comprometer além seria muito bem visto.

**Comment by maisonsakamoto** [comment]
@BENHURMARQUES já estou começando os testes na versão 3.0, já consegui transmitir com retorno de "Autorizado o uso do CT-e" pela SEFAZ, é isso mesmo que tinha postado aqui, só muda algumas tags, no meu caso eu add somente 1 tag e removi algumas que tinha, vou continuar os testes, mas acho que do jeito que esta indo... teremos uma versão estável ainda nesse primeiro semestre.

**Comment by BENHURMARQUES** [comment]
Muito bom @maisonsakamoto, quando estiver disponível me avisa que vou testar aqui também.

**Comment by realfabecker** [comment]
Ótima notícia @maisonsakamoto, disponível também para realização de testes.

**Comment by maisonsakamoto** [comment]
pessoal muda a Branch para a Versão 3.0 e da uma olhada na pasta examples, eu coloquei um arquivo lá p/ testarem:
https://github.com/nfephp-org/sped-cte/blob/v3.0/examples/testaMakeCTe.php

Com esse arquivo eu transmiti e recebi autorizacao da SEFAZ ( em ambiente homologação )

**Comment by maisonsakamoto** [comment]
se quiserem podem acompanhar a evolução da versão 3.0 por aqui:
https://gitter.im/nfephp-org/sped-cte

nesse canal podemos entrar com mais detalhes sobre o desenv.
Obrigado!

**Comment by maisonsakamoto** [comment]
@BENHURMARQUES meu co-piloto de programação esta arrebentando aqui já iniciou uma versão em produção e estamos acompanhando, segunda-feira provavelmente já teremos uma versão 3.0 release(ainda a confirmar)

**Comment by cacio** [comment]
@maisonsakamoto , cara sabe se modelo do documento fiscal: 67 que seria CT-e OS, vai ser incluído nessa 3.0 ?

**Comment by maisonsakamoto** [comment]
Oi @cacio sim esta no Manual as alterações do modelo 67

**Comment by maisonsakamoto** [comment]
pagina 61 p/ frente

**Comment by maisonsakamoto** [comment]
[Manual_CTe_v3_00.pdf](https://github.com/nfephp-org/sped-cte/files/1029992/Manual_CTe_v3_00.pdf)

**Comment by maisonsakamoto** [comment]
Assim que a https://github.com/nfephp-org/sped-cte/pull/105 entrar no projeto esta finalizado a versão estável 3.0

**Comment by maisonsakamoto** [comment]
@BENHURMARQUES esta ok a versão 3.0 na branch V3.0

As demais versões irão ser mantidas no projeto, mas serão descontinuada, na branch você já pode usar em produção normalmente, mas provavelmente iremos copiar a branch v3.0 para a master e nessa tag master manter as versões estáveis.
*lembrando que do jeito que esta já na tag v3.0 já é a primeira versão estável
