### ISSUE TITLE
Contingência

### ISSUE THREAD

**Issue by thiagoreri** [nfephp-org/sped-cte#97]
Não vi o método de ativar a contingência. Ele existi?

**Comment by maisonsakamoto** [comment]
no testaMakeCTe.php esta assim:

    $chave = $cte->montaChave(

    $cUF = '41', // Codigo da UF da tabela do IBGE: 41-PR

    $ano = date('y', strtotime($dhEmi)),

    $mes = date('m', strtotime($dhEmi)),

    $cnpj = $cteTools->aConfig['cnpj'],

    $mod = '57', // Modelo do documento fiscal: 57 para identificação do CT-e

    $serie = '2', // Serie do CTe

    $numero = $numeroCTE, // Numero do CTe

    $tpEmis = '1', // Forma de emissao do CTe: 1-Normal; 4-EPEC pela SVC; 5-Contingência

    $cCT = '10' // Codigo numerico que compoe a chave de acesso
    );               

Então acredito que basta mudar o $tpEmis na hora de montar a chave de acesso que já estará emitindo em modo contingência

**Comment by thiagoreri** [comment]
Fiz os testes, realmente não está funcionando. Não está compatível com as urls de contingencia do cte.

**Comment by robmachado** [comment]
A parte de contingência não está muito clara nessas classes.
Mas isso deve ser estabelecido na classe Tools e não apenas na classe Make.
A classe Make é apenas a construtora do XML e ela não causa o direcionamento automático para o servidor correto (mas poderia causar), especificamente no caso de envio de CTe, nos outros processos como eventos teríamos que carregar as informações referentes à contingência nas propriedades da classe (veja a classe BaseTools.php).
Para que haja o redirecionamento para as URLs corretas, falta um método na classe setContingencia() ou algo que o valha. E ainda existem códigos e endereçamentos nessa classe que não dizem respeito ao CTe.
Apenas para efeito de um exemplo que que poderia ser feito vejam https://github.com/nfephp-org/sped-nfe/blob/v5.0/docs/Contingency.md

**Comment by thiagoreri** [comment]
No arquivo cte_ws2.xml não possui as URLS para SVCRS E SVCSP, alem de que no BaseTools essas duas formas de contingencia não são tratadas.

**Comment by robmachado** [comment]
Só para complementar, a classe Tools deveria e apenas poderia lidar com contingências do tipo ON LINE como SVCRS e SVCSP, além do EPEC (que é outra tranqueira e mais complicada de usar).

**Comment by robmachado** [comment]
A classe common/Contingency.php deve ser refatorada para operar com os modos de contingência do CTe o que está la não atente o projeto.
